apiVersion: v1
kind: Pod
metadata:
  name: k8-demo
spec:
  containers:
  - name: hackon
    image: xxradar/hackon
  - name: sidecar
    image: dockersec/kubectl
    ports:
        - containerPort: 8001
