apiVersion: v1
kind: Pod
metadata:
  name: k8-demo-kubectl
spec:
  containers:
  - name: hackon
    image: nginx:latest #make sure it keeps running
  - name: sidecar
    image: dockersec/kubectl
    ports:
        - containerPort: 8001

